gearbox_api:
    resource: "@GearboxApiBundle/Resources/config/routing.yml"
    prefix:   /api/
    type: rest

gearbox_client:
    resource: "@GearboxClientBundle/Resources/config/routing.yml"
    prefix:   /

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.yml"
    prefix: /monitor/health