gearbox_client:
    resource: "@GearboxClientBundle/Resources/config/routing.yml"
    prefix:   /

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.yml"
    prefix: /monitor/health