parameters:
#    gearbox_client.example.class: Gearbox\ClientBundle\Example

services:
#    gearbox_client.example:
#        class: %gearbox_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
